kind: pipeline
type: docker
name: default
steps:
  - name: test
    image: docker
    environment:
      GO111MODULE: "on"
    commands:
      - apk update && apk add go
      - apk add libc-dev
      - apk add --no-cache git
      - apk add openrc --no-cache
      - docker run hello-world
      - go test -v ./...
