kind: pipeline
type: docker
name: default
steps:
  - name: test
    image: golang:1.14
    environment:
      GO111MODULE: "on"
    commands:
      - go test -v ./...

# services:
# - name: database
#   image: postgres:9-alpine
#   environment:
#     POSTGRES_USER: postgres
#     POSTGRES_DB: test
volumes:
  - name: v
    host:
        name: a
        path: /var/run/docker.sock:/var/run/docker.sock