kind: pipeline
type: kubernetes
name: default

steps:
- name: docker
  image: docker:dind
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  commands:
  - docker ps -a

- name: test
  image: golang:1.12
  environment:
    GOPATH: /drone
    GO111MODULE: "on"
  commands:
  - sleep 20
  - docker -v
  - make test
