kind: pipeline
name: default

steps:
- name: fetch
  image: docker:git
  commands:
  - git fetch --tags

- name: test
  image: golang:1.12
  environment:
    GOPATH: /drone
    GO111MODULE: "on"
  commands:
  - sleep 20
  - docker -v
  - make test

services:
  - name: docker
    image: docker