kind: pipeline
name: default

steps:
- name: fetch
  image: docker:git
  commands:
  - git fetch --tags

- name: test
  image: golang:1.13
  environment:
    GOPATH: /drone
    GO111MODULE: "on"
  commands:
  - make test