kind: pipeline
type: docker
name: default

steps:
- name: fetch
  image: docker:git
  commands:
  - git fetch --tags

- name: test
  image: golang:1.14
  environment:
    GO111MODULE: "on"
  commands:
  - make test