kind: pipeline
type: kubernetes
name: default
steps:
  - name: test
    image: golang:1.14
    environment:
      GO111MODULE: "on"
    commands:
      - sleep 20
      - go test -v ./...

services:
- name: localhost
  image: postgres:9-alpine
  environment:
    POSTGRES_USER: postgres
    POSTGRES_DB: test
    POSTGRES_PASSWORD: mysecretpassword