kind: pipeline
type: docker
name: default
steps:
  - name: test
    image: plugins/docker
    environment:
      GO111MODULE: "on"
    commands:
      - apk update && apk add go
      - apk add libc-dev
      - apk add --no-cache git
      - apk --no-cache add curl
      - curl --unix-socket /var/run/docker.sock http://docker/containers/json
      - go test -v ./...
