kind: pipeline
type: docker
name: default
steps:
  - name: test
    image: docker:dind
    environment:
      GOPATH: /drone
      GO111MODULE: "on"
    commands:
      - service docker start
      - apk update && apk add go
      - go test -v ./...
