kind: pipeline
type: docker
name: default
steps:
  - name: test
    image: docker:dind
    environment:
      GOPATH: /drone
      GO111MODULE: "on"
    commands:
      - docker run -v /var/run/docker.sock:/var/run/docker.sock
      - apk update && apk add go
      - go test -v ./...
