kind: pipeline
type: docker
name: default
steps:
  - name: test
    image: docker:19.03.0-dind
    environment:
      GOPATH: /drone
      GO111MODULE: "on"
    commands:
      - apk update && apk add go
      - go test -v ./...
