kind: pipeline
type: kubernetes
name: default

steps:
- name: dockerInstall
  image: plugins/docker:latest
  commands:
  - docker -v  

- name: test
  image: golang:1.14
  commands:
  - docker -v  
  - go build
  - go test ./...